"""
Django settings for parentscourse_server project.

Generated by 'django-admin startproject' using Django 2.1.8.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

from parentscourse_server.config import version

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '4a(3zd*$ek6ujq$h)$u@0(1^*9-w22qaik-zie&89ooflab7!6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# 缓存过期时间
USER_SESSION_OVER_TIME = 7 * 24 * 60 * 60

ALLOWED_HOSTS = [
    '127.0.0.1',
    '192.168.100.201',
    '192.168.100.166',
    '192.168.100.253',
    '192.168.100.252',
    '192.168.100.235',
    '192.168.100.199',
    '192.168.100.194',
    '192.168.100.51',
    '192.168.100.115',
    '192.168.100.254',
    '172.17.0.18',
    '39.97.229.202',
    '28eu182584.zicp.vip'
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'django_filters',
    'manager',
    'manager_rabc',
    'manager_user',
    'manager_coupons',
    'manager_order',
    'manager_course',
    'manager_comments',
    'manager_auth',
    'manager_chatroom',
    'client',
    'common',
    'public',
    'dwebsocket',
    'manager_distribution',
    'haystack',
    'django_apscheduler',
    'im_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # 跨域相关中间件
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'parentscourse_server.urls'

WEBSOCKET_ACCEPT_ALL = True  # 可以允许每一个单独的视图实用websockets

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates/"), ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'parentscourse_server.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

if version == 'debug':
    # DATABASES = {
    #     'default': {
    #         'ENGINE': 'django.db.backends.mysql',  # 数据库引擎
    #         'NAME': 'hbb_course2',  # 储数据的库名
    #         'USER': 'root',  # 数据库用户名
    #         'PASSWORD': 'hbb123',  # 密码
    #         'HOST': '127.0.0.1',  # 主机
    #         'PORT': '3306',  # 数据库使用的端口
    #         'OPTIONS': {
    #             'charset': 'utf8mb4',
    #             'use_unicode': True, },
    #     }
    # }
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',  # 数据库引擎
            'NAME': 'hbb_course2',  # 储数据的库名
            'USER': 'root',  # 数据库用户名
            'PASSWORD': 'hbb123',  # 密码
            'HOST': '192.168.100.235',  # 主机
            'PORT': '3306',  # 数据库使用的端口
            'OPTIONS': {
                'charset': 'utf8mb4',
                'use_unicode': True,
            },
        }
    }
    # 缓存配置
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': [
                'redis://127.0.0.1:6379/0',
            ],  # redis服务ip和端口，
            'KEY_PREFIX': 'manage',
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'CONNECTION_POOL_KWARGS': {
                    'max_connections': 1024,
                }
            },
        },
        'client': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': [
                'redis://127.0.0.1:6379/1',
            ],  # redis服务ip和端口，
            'KEY_PREFIX': 'client',
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'CONNECTION_POOL_KWARGS': {
                    'max_connections': 512,
                }
            },
        },
    }

    # Haystack
    HAYSTACK_CONNECTIONS = {
        'default': {
            'ENGINE': 'haystack.backends.elasticsearch_backend.ElasticsearchSearchEngine',
            'URL': 'http://192.168.100.235:9200/',  # 此处为elasticsearch运行的服务器ip地址，端口号固定为9200
            'INDEX_NAME': 'hbb_course',  # 指定elasticsearch建立的索引库的名称
        },
    }

    # 当添加、修改、删除数据时，自动生成索引
    HAYSTACK_SIGNAL_PROCESSOR = 'haystack.signals.RealtimeSignalProcessor'

    # 指定搜索结果每页的条数 这里设置成了1条
    HAYSTACK_SEARCH_RESULTS_PER_PAGE = 1
elif version == 'test':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',  # 数据库引擎
            'NAME': 'hbb_course2',  # 储数据的库名
            'USER': 'root',  # 数据库用户名
            'PASSWORD': 'hbb123',  # 密码
            'HOST': '192.168.100.235',  # 主机
            'PORT': '3306',  # 数据库使用的端口
            'OPTIONS': {
                'charset': 'utf8mb4',
                'use_unicode': True, },
        }
    }
    # 缓存配置
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': [
                'redis://172.17.0.20:6379/0',
            ],  # redis服务ip和端口，
            'KEY_PREFIX': 'manage',
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'CONNECTION_POOL_KWARGS': {
                    'max_connections': 1024,
                }
            },
        },
        'client': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': [
                'redis://172.17.0.20:6379/1',
            ],  # redis服务ip和端口，
            'KEY_PREFIX': 'client',
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'CONNECTION_POOL_KWARGS': {
                    'max_connections': 512,
                }
            },
        },
    }

    # Haystack
    HAYSTACK_CONNECTIONS = {
        'default': {
            'ENGINE': 'haystack.backends.elasticsearch_backend.ElasticsearchSearchEngine',
            'URL': 'http://172.17.0.4:9200/',  # 此处为elasticsearch运行的服务器ip地址，端口号固定为9200
            'INDEX_NAME': 'hbb_course',  # 指定elasticsearch建立的索引库的名称
        },
    }

    # 当添加、修改、删除数据时，自动生成索引
    HAYSTACK_SIGNAL_PROCESSOR = 'haystack.signals.RealtimeSignalProcessor'

    # 指定搜索结果每页的条数 这里设置成了1条
    HAYSTACK_SEARCH_RESULTS_PER_PAGE = 1
elif version == 'ali_test':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',  # 数据库引擎
            'NAME': 'hbb_course',  # 储数据的库名
            'USER': 'root',  # 数据库用户名
            'PASSWORD': 'hbb123',  # 密码
            'HOST': '39.97.229.202',  # 主机
            'PORT': '3306',  # 数据库使用的端口
            'OPTIONS': {
                'charset': 'utf8mb4',
                'use_unicode': True, },
        }
    }
    # 缓存配置
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': [
                'redis://39.97.229.202:6379/0',
            ],  # redis服务ip和端口，
            'KEY_PREFIX': 'manage',
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'CONNECTION_POOL_KWARGS': {
                    'max_connections': 1024,
                },
                'PASSWORD': 'hbb123',
            },
        },
        'client': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': [
                'redis://39.97.229.202:6379/1',
            ],  # redis服务ip和端口，
            'KEY_PREFIX': 'client',
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'CONNECTION_POOL_KWARGS': {
                    'max_connections': 512,
                },
                'PASSWORD': 'hbb123',
            },
        },
    }
    # Haystack
    HAYSTACK_CONNECTIONS = {
        'default': {
            'ENGINE': 'haystack.backends.elasticsearch_backend.ElasticsearchSearchEngine',
            'URL': 'http://172.18.0.5:9200/',  # 此处为elasticsearch运行的服务器ip地址，端口号固定为9200
            'INDEX_NAME': 'hbb_course',  # 指定elasticsearch建立的索引库的名称
        },
    }

    # 当添加、修改、删除数据时，自动生成索引
    HAYSTACK_SIGNAL_PROCESSOR = 'haystack.signals.RealtimeSignalProcessor'

    # 指定搜索结果每页的条数 这里设置成了1条
    HAYSTACK_SEARCH_RESULTS_PER_PAGE = 1

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

# 跨域攻击配置
CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_ALLOW_ALL = True

# 配置允许跨站访问本站的地址
CORS_ORIGIN_WHITELIST = (
    'http://screentest.hbbclub.com',
    'http://shoptest.hbbclub.com'
)
CORS_ALLOW_METHODS = (
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
    'VIEW',
)
CORS_ALLOW_HEADERS = (
    'Content-Type',
    'token',
    'Content-Length',
    'Accept-Encoding',
    'X-CSRF-Token',
    'Authorization',
    'accept',
    'origin',
    'Cache-Control',
    'X-Requested-With',
    'XSRF-TOKEN',
    'X-XSRF-TOKEN'
)

LOGGING = {
    'version': 1,
    # 是否禁用已经存在的日志器
    'disable_existing_loggers': False,
    # 日志格式化器
    'formatters': {
        'simple': {
            'format': '%(asctime)s %(module)s.%(funcName)s: %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        # 详细
        'verbose': {
            'format': '%(asctime)s %(levelname)s [%(process)d-%(threadName)s] '
                      '%(module)s.%(funcName)s line %(lineno)d: %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        }
    },
    'filters': {
        # 只有在Django配置文件中DEBUG值为True时才起作用
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        # 输出到控制台
        'console': {
            'class': 'logging.StreamHandler',
            'level': 'DEBUG',
            'filters': ['require_debug_true'],
            'formatter': 'verbose',
        },
        # 输出到文件(每周切割一次)
        'file1': {
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': 'logs/access.log',
            'when': 'W0',
            'backupCount': 12,  # 备份份数
            'formatter': 'simple',  # 使用哪种formatters日志格式
            'level': 'DEBUG',
            'encoding': 'utf-8',  # 设置默认编码
        },
        # 输出到文件(每天切割一次)
        'file2': {
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': 'logs/error.log',
            'when': 'D',
            'backupCount': 31,
            'formatter': 'verbose',
            'level': 'WARNING',
            'encoding': 'utf-8',  # 设置默认编码
        },
        # 输出到文件(每周切割一次) -- 用户访问IP和访问的路径
        'file3': {
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': 'logs/ipandpath.log',
            'when': 'W0',
            'backupCount': 12,  # 备份份数
            'formatter': 'simple',  # 使用哪种formatters日志格式
            'level': 'INFO',
            'encoding': 'utf-8',  # 设置默认编码
        },
    },
    # CRITICAL > ERROR > WARNING > INFO > DEBUG > NOTEST
    'loggers': {
        'django': {
            # 需要使用的日志处理器
            'handlers': ['console', 'file1', 'file2'],
            # 是否向上传播日志信息
            'propagate': True,
            'level': 'DEBUG',
        },
        'ipandpath': {
            # 需要使用的日志处理器
            'handlers': ['file3'],
            # 是否向上传播日志信息
            'propagate': False,
            'level': 'INFO',
        },
    }
}

REST_FRAMEWORK = {
    # 分页配置
    'DEFAULT_PAGINATION_CLASS': 'utils.paginations.MyPagination',
    'PAGE_SIZE': 100,
    # 过滤
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),


    'DEFAULT_THROTTLE_CLASSES': (
        # 'rest_framework.throttling.AnonRateThrottle',
        # 'rest_framework.throttling.UserRateThrottle'
        'rest_framework.throttling.ScopedRateThrottle',  # throttle_scope = 'uploads'
    ),
    'DEFAULT_THROTTLE_RATES': {
        # 'anon': '1/d',
        # 'user': '5/m',
        'sms': '5/d',
    },



    # 重构renderer
    'DEFAULT_RENDERER_CLASSES': (
        'utils.renderer.MyJsonRenderer',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'utils.auths.CustomAuthentication',
        'utils.auths.IMAuthentication',
        'utils.clientAuths.ClientAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'utils.auths.CustomAuthorization',
    ),
    'EXCEPTION_HANDLER': 'utils.exceptions.custom_exception_handler'
}
APPEND_SLASH = False

